# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_FunD_rcpp_hello_world', PACKAGE = 'FunD')
}

RFD <- function(x, n, m, q) {
    .Call('_FunD_RFD', PACKAGE = 'FunD', x, n, m, q)
}

FDq0 <- function(n, f1, f2, h1, h2, A) {
    .Call('_FunD_FDq0', PACKAGE = 'FunD', n, f1, f2, h1, h2, A)
}

FDq1_1 <- function(n, h1, A) {
    .Call('_FunD_FDq1_1', PACKAGE = 'FunD', n, h1, A)
}

FDq2 <- function(tmpxv, n) {
    .Call('_FunD_FDq2', PACKAGE = 'FunD', tmpxv, n)
}

delta <- function(del_avtab, k, n) {
    .Call('_FunD_delta', PACKAGE = 'FunD', del_avtab, k, n)
}

